azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
networks:
- name: default
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: random
    gateway: 10.244.142.1
    range: 10.244.142.0/24
    reserved:
    - 10.244.142.1
    static:
    - 10.244.142.2 - 10.244.142.60
- name: public
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: random
    gateway: 10.244.32.1
    range: 10.244.32.0/19
    reserved:
    - 10.244.32.1
    static:
    - 10.244.32.2 - 10.244.32.255
vm_extensions:
- name: 5GB_ephemeral_disk
- name: 10GB_ephemeral_disk
- name: 50GB_ephemeral_disk
- name: 100GB_ephemeral_disk
- name: 500GB_ephemeral_disk
- name: 1TB_ephemeral_disk
vm_types:
- name: default
- name: m3.medium
- name: m3.large
- name: m3.xlarge
- name: m3.2xlarge
- name: m4.large
- name: m4.xlarge
- name: m4.2xlarge
- name: m4.4xlarge
- name: m4.10xlarge
- name: c3.large
- name: c3.xlarge
- name: c3.2xlarge
- name: c3.4xlarge
- name: c3.8xlarge
- name: c4.large
- name: c4.xlarge
- name: c4.2xlarge
- name: c4.4xlarge
- name: c4.8xlarge
- name: r3.large
- name: r3.xlarge
- name: r3.2xlarge
- name: r3.4xlarge
- name: r3.8xlarge